language: python
python:
    - "3.8"
- name: Codecov
  uses: codecov/codecov-action@v1.0.13
install:
#    - pip install -e .
    - pip install pytest-cov codecov
script:
    - pytest --cov=src tests
after_success:
    - codecov
    
